import { useState, type FormEvent } from 'react'
import { CalendarCheck, CalendarDays, Check, FileText, Plus, Star, Target, TrendingUp } from 'lucide-react'
import { Badge, EmptyState, Modal, ProgressBar, SectionHeading, StatCard, TableShell } from '../components/ui.js'
import { useHrms } from '../state/useHrms.js'
import { formatDate, statusTone } from '../utils/format.js'
import type { GoalInput, HrmsSnapshot, PerformanceCycleInput, PerformanceRecord, PerformanceReviewInput } from '../types/hrms.js'

const personName = (data: HrmsSnapshot, employeeId: string) => {
  const employee = data.employees.find((item) => item.id === employeeId)
  return employee ? `${employee.firstName} ${employee.lastName}` : employeeId
}
const reviewMetrics: Array<[keyof Pick<PerformanceReviewInput, 'score' | 'goalProgress' | 'quality' | 'productivity' | 'teamwork'>, string]> = [
  ['score', 'Overall score'], ['goalProgress', 'Goal progress'], ['quality', 'Quality'], ['productivity', 'Productivity'], ['teamwork', 'Teamwork'],
]

export default function AdminPerformanceOperations() {
  const { data, savePerformance, publishPerformance, createPerformanceCycle, saveGoal } = useHrms()
  const [reviewForm, setReviewForm] = useState<PerformanceReviewInput | null>(null)
  const [showCycle, setShowCycle] = useState(false)
  const [showGoal, setShowGoal] = useState(false)
  const defaultEmployee = data?.employees.find((item) => item.role === 'employee' && item.status === 'Active')?.id ?? ''
  const defaultCycle = data?.performanceCycles.find((item) => item.status === 'Active')
  const [cycleForm, setCycleForm] = useState<PerformanceCycleInput>({ title: 'Quarterly Performance Cycle', period: `Q${Math.floor(new Date().getMonth() / 3) + 1} ${new Date().getFullYear()}`, status: 'Active', startDate: '', endDate: '' })
  const [goalForm, setGoalForm] = useState<GoalInput>({ employeeId: defaultEmployee, title: '', description: '', category: 'Growth', progress: 0, status: 'Active', dueDate: '' })
  if (!data) return null

  const openReview = (review?: PerformanceRecord) => setReviewForm(review ? { ...review, comments: review.comments ?? '', cycleId: review.cycleId ?? '' } : { employeeId: defaultEmployee, cycleId: defaultCycle?.id ?? '', period: defaultCycle?.period ?? `Q${Math.floor(new Date().getMonth() / 3) + 1} ${new Date().getFullYear()}`, score: 80, goalProgress: 80, quality: 80, productivity: 80, teamwork: 80, comments: '' })
  const submitReview = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault()
    if (!reviewForm) return
    const score = Number(reviewForm.score)
    const rating = score >= 90 ? 'Outstanding' : score >= 80 ? 'Exceeds expectations' : score >= 70 ? 'Meets expectations' : 'Needs improvement'
    try { await savePerformance({ ...reviewForm, rating }); setReviewForm(null) } catch { /* Keep private draft open. */ }
  }
  const submitCycle = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); try { await createPerformanceCycle(cycleForm); setShowCycle(false) } catch { /* Keep form open. */ } }
  const submitGoal = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); try { await saveGoal(goalForm); setShowGoal(false); setGoalForm({ ...goalForm, title: '', description: '', progress: 0, dueDate: '' }) } catch { /* Keep form open. */ } }

  return <div className="page-stack">
    <SectionHeading eyebrow="Draft before disclosure" title="Performance & Growth" description="Run review cycles, save private drafts, publish intentionally, and maintain employee goals." actions={<><button className="button button-secondary" onClick={() => setShowCycle(true)}><CalendarDays />New cycle</button><button className="button button-secondary" onClick={() => setShowGoal(true)}><Target />Add goal</button><button className="button button-primary" onClick={() => openReview()}><Plus />New review</button></>} />
    <div className="stats-grid stats-grid-3"><StatCard icon={CalendarCheck} label="Active cycles" value={data.performanceCycles.filter((item) => item.status === 'Active').length} tone="blue" /><StatCard icon={FileText} label="Draft reviews" value={data.performance.filter((item) => item.status === 'Draft').length} tone="amber" /><StatCard icon={TrendingUp} label="Active goals" value={data.goals.filter((item) => item.status === 'Active').length} tone="green" /></div>
    <section className="panel"><div className="panel-header"><div><h2>Review records</h2><p>Employees retrieve only Published records through RLS.</p></div></div>{data.performance.length ? <TableShell><thead><tr><th>Employee</th><th>Period</th><th>Score</th><th>Goal progress</th><th>Rating</th><th>Status / Action</th></tr></thead><tbody>{data.performance.map((review) => <tr key={review.id}><td><strong>{personName(data, review.employeeId)}</strong><small className="table-subtitle">{review.employeeId}</small></td><td>{review.period}</td><td><strong>{review.score}/100</strong></td><td>{review.goalProgress}%</td><td>{review.rating}</td><td><div className="table-actions"><Badge tone={statusTone(review.status)}>{review.status}</Badge><button className="mini-button" onClick={() => openReview(review)}>Edit</button>{review.status === 'Draft' && <button className="mini-button approve" onClick={() => void publishPerformance(review.id)}><Check />Publish</button>}</div></td></tr>)}</tbody></TableShell> : <EmptyState icon={Star} title="No performance reviews" text="Create a draft, review it, then publish it to the employee." />}</section>
    <section className="panel"><div className="panel-header"><div><h2>Employee goals</h2><p>Shared progress values for coaching conversations</p></div></div><div className="goal-admin-grid">{data.goals.map((goal) => <article key={goal.id}><div><Badge tone={statusTone(goal.status)}>{goal.status}</Badge><h3>{goal.title}</h3><p>{personName(data, goal.employeeId)} · {goal.category} · Due {formatDate(goal.dueDate)}</p></div><strong>{goal.progress}%</strong><ProgressBar value={goal.progress} label="Progress" /></article>)}</div></section>
    {reviewForm && <Modal title="Save performance review draft" onClose={() => setReviewForm(null)} size="large"><form className="form-grid" onSubmit={submitReview}><label>Employee<select value={reviewForm.employeeId} onChange={(event) => setReviewForm({ ...reviewForm, employeeId: event.target.value })}>{data.employees.filter((item) => item.role === 'employee').map((item) => <option value={item.id} key={item.id}>{item.firstName} {item.lastName}</option>)}</select></label><label>Cycle<select value={reviewForm.cycleId} onChange={(event) => { const cycle = data.performanceCycles.find((item) => item.id === Number(event.target.value)); setReviewForm({ ...reviewForm, cycleId: event.target.value, period: cycle?.period ?? reviewForm.period }) }}><option value="">No cycle</option>{data.performanceCycles.map((item) => <option value={item.id} key={item.id}>{item.period} · {item.status}</option>)}</select></label><label className="span-2">Review period<input value={reviewForm.period} onChange={(event) => setReviewForm({ ...reviewForm, period: event.target.value })} required /></label>{reviewMetrics.map(([key, label]) => <label key={key}>{label}<input type="number" min={0} max={100} value={reviewForm[key]} onChange={(event) => setReviewForm({ ...reviewForm, [key]: Number(event.target.value) })} required /></label>)}<label className="span-2">Comments<textarea rows={4} maxLength={1000} value={reviewForm.comments} onChange={(event) => setReviewForm({ ...reviewForm, comments: event.target.value })} /></label><p className="form-note span-2">Saving creates a private draft. Use Publish only after the review is complete and approved for employee disclosure.</p><div className="modal-actions span-2"><button type="button" className="button button-secondary" onClick={() => setReviewForm(null)}>Cancel</button><button className="button button-primary">Save private draft</button></div></form></Modal>}
    {showCycle && <Modal title="Create performance cycle" onClose={() => setShowCycle(false)}><form className="form-grid" onSubmit={submitCycle}><label className="span-2">Cycle title<input value={cycleForm.title} onChange={(event) => setCycleForm({ ...cycleForm, title: event.target.value })} required /></label><label>Period label<input value={cycleForm.period} onChange={(event) => setCycleForm({ ...cycleForm, period: event.target.value })} required /></label><label>Status<select value={cycleForm.status} onChange={(event) => setCycleForm({ ...cycleForm, status: event.target.value })}><option>Draft</option><option>Active</option><option>Review</option><option>Closed</option></select></label><label>Start date<input type="date" value={cycleForm.startDate} onChange={(event) => setCycleForm({ ...cycleForm, startDate: event.target.value })} /></label><label>End date<input type="date" value={cycleForm.endDate} onChange={(event) => setCycleForm({ ...cycleForm, endDate: event.target.value })} /></label><div className="modal-actions span-2"><button type="button" className="button button-secondary" onClick={() => setShowCycle(false)}>Cancel</button><button className="button button-primary">Create cycle</button></div></form></Modal>}
    {showGoal && <Modal title="Assign employee goal" onClose={() => setShowGoal(false)}><form className="form-grid" onSubmit={submitGoal}><label className="span-2">Employee<select value={goalForm.employeeId} onChange={(event) => setGoalForm({ ...goalForm, employeeId: event.target.value })}>{data.employees.filter((item) => item.role === 'employee').map((item) => <option value={item.id} key={item.id}>{item.firstName} {item.lastName}</option>)}</select></label><label className="span-2">Goal title<input value={goalForm.title} onChange={(event) => setGoalForm({ ...goalForm, title: event.target.value })} required /></label><label>Category<input value={goalForm.category} onChange={(event) => setGoalForm({ ...goalForm, category: event.target.value })} required /></label><label>Due date<input type="date" value={goalForm.dueDate} onChange={(event) => setGoalForm({ ...goalForm, dueDate: event.target.value })} required /></label><label className="span-2">Description<textarea rows={4} value={goalForm.description} onChange={(event) => setGoalForm({ ...goalForm, description: event.target.value })} /></label><div className="modal-actions span-2"><button type="button" className="button button-secondary" onClick={() => setShowGoal(false)}>Cancel</button><button className="button button-primary">Assign goal</button></div></form></Modal>}
  </div>
}
