// Change a version whenever its corresponding notice changes. The server imports
// these same identifiers and stores acceptance in protected Auth app_metadata.
export const TERMS_VERSION = '2026-09-30.2'
export const PRIVACY_VERSION = '2026-09-30.2'

export const policyContact = {
  organization: 'Quantumn Art Resources — Academic HRMS Project',
  email: 'quantumnhr@gmail.com',
  role: 'Project Privacy Coordinator (academic project role)',
  location: 'Metro Manila, Philippines — illustrative project location, not a verified postal address',
}

export const policyReferences = [
  { title: 'Republic Act No. 10173 — Data Privacy Act of 2012', url: 'https://privacy.gov.ph/data-privacy-act/' },
  { title: 'Implementing Rules and Regulations of the Data Privacy Act', url: 'https://privacy.gov.ph/implementing-rules-regulations-data-privacy-act-2012/' },
  { title: 'NPC Guidelines on Consent — Circular No. 2023-04', url: 'https://privacy.gov.ph/wp-content/uploads/2023/11/NPC-Circular-No.-2023-04_Guidelines-on-Consent_07Nov2023.pdf' },
  { title: 'Your data subject rights', url: 'https://privacy.gov.ph/data-subject-rights/' },
  { title: 'How to file a complaint with the NPC', url: 'https://privacy.gov.ph/file-a-complaint-2/' },
]

export const accountPolicies = [
  {
    id: 'terms', title: 'Terms and Conditions', version: TERMS_VERSION,
    introduction: 'Effective September 30, 2026. These terms cover the Quantumn Art Resources academic HRMS demonstration at quantumnhr.com. The organization and office details are illustrative; the website’s account and security functions are real. Use fictional HR records for demonstrations. These terms do not replace an employment agreement or rights protected by Philippine law.',
    sections: [
      ['Use your own account', 'Use the account issued to you for authorized work and HR tasks. Keep your password, email verification codes, authenticator codes, and recovery links private. Do not share access or attempt to view records outside your assigned permissions.'],
      ['Keep submissions accurate', 'Provide accurate information when submitting attendance corrections, leave requests, HR requests, and other records. Contact HR when an employment record needs correction. A submission is not an approval; follow the status and response shown in the portal.'],
      ['Handle information responsibly', 'Use employee records and downloaded documents only for their authorized purpose. Do not misuse, redistribute, or expose another person’s personal information. Report suspected unauthorized access to your organization’s HR team or System Administrator.'],
      ['Account access and support', 'Your organization manages your account, role, and employment records. Access may change when your role or employment status changes. If you cannot use the portal or disagree with these terms, sign out and contact HR to discuss an appropriate way to complete your HR tasks.'],
      ['Records, availability, and decisions', 'Review your submissions and report errors through Request Center. Keep the reference number for important requests. Portal calculations, warnings, and draft records do not replace authorized HR decisions. If the service is unavailable, use your established HR contact; these terms do not extend a statutory deadline or remove an entitlement because of an outage.'],
      ['Privacy and electronic acknowledgment', 'The separate Privacy Notice explains how this HRMS handles personal data. Your agreement to these terms and acknowledgment of that notice are recorded electronically with the document versions and time. They do not authorize unrelated processing, waive privacy rights, or serve as consent for every future use of employee data.'],
      ['Philippine law and your rights', 'Applicable Philippine law governs these terms, including the Data Privacy Act of 2012 and mandatory labor protections. Nothing here waives statutory wages, benefits, due process, privacy remedies, or access to DOLE, the National Labor Relations Commission, the National Privacy Commission, or the proper courts. No mandatory arbitration, blanket indemnity, or release of the organization’s legal responsibilities is imposed by these terms.'],
      ['Changes to these terms', 'A revised document must carry a new version and effective date. Material changes should be brought to employees’ attention before taking effect. A later update cannot retroactively authorize a new processing purpose or waive an existing right. You may revisit the current Terms and Privacy Notice from the sign-in page or HR Help Center.'],
    ],
  },
  {
    id: 'privacy', title: 'Privacy Notice', version: PRIVACY_VERSION,
    introduction: 'Effective September 30, 2026. This notice is for the Quantumn Art Resources academic HRMS project, drafted with reference to Republic Act No. 10173, its Implementing Rules and Regulations, and NPC guidance. Academic use does not remove privacy responsibilities for real account information. Acknowledgment is not blanket consent or a waiver of your rights.',
    sections: [
      ['Project identity and privacy contact', 'The project team operating this academic HRMS is responsible for the account information it decides to collect and use. Quantumn Art Resources is the demonstration organization, not a representation of a registered employer. The project-provided contact is quantumnhr@gmail.com, addressed to the Project Privacy Coordinator. Mailbox ownership and monitoring have not been verified. “Metro Manila, Philippines” is an illustrative project location, not a verified postal address, and this role is not a claim of a formally appointed or registered DPO.'],
      ['How to reach the project team', 'For a trackable privacy request, open Employee portal → Request Center → General HR and use the subject “Privacy request”. Before setup or if you cannot sign in, contact the person who issued your project account. You may use the project-provided email above after confirming it with that person; do not send sensitive records to an unverified mailbox. Before genuine employment records are introduced, the operator must publish the actual controller’s identity, address, and designated privacy contact.'],
      ['Information and its sources', 'HR supplies your account and employment record; you supply requests, corrections, contact updates, and an optional photo. Authorized staff add payroll, benefits, schedules, performance, and HR documents. The system generates timestamps, session/device information, sign-in and security events, and audit records. Where collected for an authorized HR purpose, health details, government-issued identifiers, or other sensitive personal information require additional protection. Submit only relevant details, especially about other people.'],
      ['Purposes and lawful grounds', 'Account creation, work schedules, attendance, pay administration, and HR requests support the employment relationship and applicable contractual duties. Statutory payroll, tax, and employment records may require processing to meet legal obligations. Access logs and security investigations protect accounts and records; reliance on legitimate interests requires necessity and a balance against employee rights. These grounds concern ordinary personal information under Section 12 of the DPA. Each activity must have an applicable basis; this notice does not create one by itself.'],
      ['Sensitive information and optional uses', 'Health information, government identifiers, and other sensitive or privileged information need an applicable exception under Section 13 of the DPA, such as a qualifying law or specific prior consent where appropriate; ordinary legitimate interests alone are not enough. If consent is the basis for an optional activity, HR must explain the specific data, purpose, recipients, and withdrawal method separately. Refusing unrelated optional processing must not be made a condition of employment or portal access. Your profile photo is optional; this release has no facial-recognition feature.'],
      ['How the portal processes information', 'Records are stored electronically, displayed to authorized users, updated through controlled workflows, and synchronized through Supabase Realtime. The portal calculates values such as leave duration and payroll drafts and produces security indicators from recorded events. These are operational aids, not a substitute for human review of a disputed employment decision. Ask HR to explain or correct a result that affects you. No advertising trackers or marketing purpose are authorized by this notice.'],
      ['Access, recipients, and service providers', 'Access depends on assigned roles: employees view their available records; authorized HR, payroll, security, system administrators, and auditors receive access for their responsibilities. Supabase supplies authentication, database, realtime, and private file storage; Netlify hosts the website and server functions; Resend delivers application email. Providers may process data outside the Philippines. The controller remains responsible for appropriate safeguards and processor arrangements. Disclosures to government bodies, benefit providers, or advisers require a relevant purpose and lawful basis, not unrestricted sharing.'],
      ['Retention and disposal', 'Employment and financial records must be retained only for their declared purpose, applicable legal duties, or a justified legal claim—not indefinitely for an unspecified future use. Different record categories have different requirements; HR must maintain and provide the applicable retention schedule, including any lawful hold. Account closure does not automatically erase required records. When retention is no longer justified, authorized staff must arrange secure deletion or irreversible anonymization, including appropriate treatment of copies and backups. This release does not claim that all record categories already have automatic deletion schedules.'],
      ['Security and incidents', 'The portal uses encrypted HTTPS connections, account and role checks, row-level access controls, private photo storage, session controls, and audit records. Keep passwords, codes, and recovery links private and report unfamiliar activity promptly. No system can promise absolute security. The controller must assess incidents and meet applicable NPC and affected-person notification duties when a breach meets the legal notification conditions.'],
      ['Your rights', 'Subject to applicable conditions and exceptions, you may be informed about processing; access your data; request correction, erasure or blocking; object to processing; obtain a portable copy where applicable; seek damages where justified; and complain to the NPC. Withdrawal of consent affects consent-based processing, not processing still required on another valid legal ground. A request may require proportionate identity verification. If a request cannot be granted, ask HR for the reason and available review options.'],
      ['Requests and complaints', 'Use the HR contact route above for access, correction, retention questions, or referral to the privacy representative. In the Request Center, include the record or issue and requested action, but never your password, verification code, or reset link. Keep your request reference. The NPC’s current complaint instructions are linked below; its procedural requirements and exceptions apply. Using this portal does not waive your right to approach the Commission or another competent authority.'],
      ['Record of acknowledgment', 'When you finish account setup, the system records the versions of these terms and this notice, your agreement and acknowledgment, and the server time. Your password is not included in that acknowledgment record.'],
      ['Notice updates and academic-use limits', 'The current version remains available at /privacy. Material changes to the purposes, data, recipients, or methods must be explained before the changed activity, or at the time permitted by law; a version update is not automatic consent. Use fictional employment, salary, health, and identity-document records for class demonstrations. Before use as a real employer’s system, verify the controller and DPO contacts, retention schedule, provider arrangements, and operational compliance. This project does not claim NPC certification or legal-compliance certification.'],
    ],
  },
]

export function validSetupAcknowledgment(value) {
  return value?.termsAccepted === true && value?.privacyAcknowledged === true
    && value.termsVersion === TERMS_VERSION && value.privacyVersion === PRIVACY_VERSION
}
