-- Quantum Art Resources HRMS
-- Supabase schema, fictional seed data, authentication links, and RLS policies.

create sequence if not exists public.employee_number_seq start 1;

create table if not exists public.profiles (
  employee_code text primary key default ('EMP' || lpad(nextval('public.employee_number_seq')::text, 3, '0')),
  auth_user_id uuid unique references auth.users(id) on delete set null,
  first_name text not null,
  last_name text not null,
  email text not null unique,
  role text not null default 'employee' check (role in ('employee', 'admin', 'security_admin')),
  department text not null,
  position text not null,
  status text not null default 'Active' check (status in ('Active', 'On Leave', 'Inactive')),
  salary numeric(12, 2) not null default 0 check (salary >= 0),
  phone text,
  hire_date date not null default current_date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists profiles_email_lower_idx on public.profiles (lower(email));
create index if not exists profiles_auth_user_id_idx on public.profiles (auth_user_id);

create table if not exists public.attendance (
  id bigint generated by default as identity primary key,
  employee_code text not null references public.profiles(employee_code),
  work_date date not null default current_date,
  clock_in time,
  clock_out time,
  status text not null default 'Present' check (status in ('Present', 'Late', 'Absent', 'On Leave')),
  hours numeric(5, 2) not null default 0 check (hours >= 0 and hours <= 24),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (employee_code, work_date)
);

create index if not exists attendance_employee_date_idx
  on public.attendance (employee_code, work_date desc);

create table if not exists public.leave_requests (
  id bigint generated by default as identity primary key,
  employee_code text not null references public.profiles(employee_code),
  leave_type text not null check (leave_type in ('Vacation', 'Sick', 'Emergency', 'Other')),
  start_date date not null,
  end_date date not null,
  days integer not null check (days > 0),
  reason text not null check (char_length(reason) between 3 and 500),
  status text not null default 'Pending' check (status in ('Pending', 'Approved', 'Rejected')),
  reviewed_by text references public.profiles(employee_code),
  reviewed_at timestamptz,
  created_at timestamptz not null default now(),
  check (end_date >= start_date)
);

create index if not exists leave_requests_employee_idx
  on public.leave_requests (employee_code, created_at desc);

create table if not exists public.payroll (
  id bigint generated by default as identity primary key,
  employee_code text not null references public.profiles(employee_code),
  period text not null,
  gross numeric(12, 2) not null check (gross >= 0),
  deductions numeric(12, 2) not null default 0 check (deductions >= 0),
  net numeric(12, 2) generated always as (gross - deductions) stored,
  status text not null default 'Draft' check (status in ('Draft', 'Processed', 'Paid')),
  payment_date date,
  created_at timestamptz not null default now(),
  unique (employee_code, period)
);

create table if not exists public.performance_reviews (
  id bigint generated by default as identity primary key,
  employee_code text not null references public.profiles(employee_code),
  reviewer_code text references public.profiles(employee_code),
  period text not null,
  score integer not null check (score between 0 and 100),
  goal_progress integer not null check (goal_progress between 0 and 100),
  rating text not null,
  comments text,
  created_at timestamptz not null default now(),
  unique (employee_code, period)
);

create table if not exists public.announcements (
  id bigint generated by default as identity primary key,
  title text not null check (char_length(title) between 3 and 120),
  content text not null check (char_length(content) between 3 and 1000),
  priority text not null default 'Normal' check (priority in ('Normal', 'High')),
  author_employee_code text references public.profiles(employee_code),
  published_on date not null default current_date,
  created_at timestamptz not null default now()
);

create table if not exists public.security_alerts (
  alert_code text primary key,
  employee_code text references public.profiles(employee_code),
  severity text not null check (severity in ('Critical', 'High', 'Medium', 'Low')),
  event_type text not null,
  title text not null,
  description text not null,
  affected_label text not null,
  display_time text not null,
  status text not null default 'New' check (status in ('New', 'Investigating', 'Acknowledged', 'Resolved')),
  recommended_action text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists security_alerts_employee_idx
  on public.security_alerts (employee_code, created_at desc);

create table if not exists public.account_sessions (
  session_code text primary key,
  employee_code text not null references public.profiles(employee_code),
  device text not null,
  location text not null,
  last_active_label text not null,
  is_current boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists account_sessions_employee_idx
  on public.account_sessions (employee_code, created_at desc);

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  actor_employee_code text references public.profiles(employee_code),
  actor_label text not null,
  action text not null,
  target text not null,
  display_time text not null,
  created_at timestamptz not null default now()
);

create or replace function public.current_employee_code()
returns text
language sql
stable
security definer
set search_path = ''
as $$
  select employee_code
  from public.profiles
  where auth_user_id = (select auth.uid())
  limit 1
$$;

create or replace function public.is_hrms_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.profiles
    where auth_user_id = (select auth.uid())
      and role in ('admin', 'security_admin')
      and status = 'Active'
  )
$$;

create or replace function public.link_auth_user_to_profile()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  update public.profiles
  set auth_user_id = new.id,
      updated_at = now()
  where lower(email) = lower(new.email)
    and auth_user_id is null;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created_link_profile on auth.users;
create trigger on_auth_user_created_link_profile
  after insert on auth.users
  for each row execute procedure public.link_auth_user_to_profile();

create or replace function public.update_own_profile(new_phone text)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  if (select auth.uid()) is null then
    raise exception 'Authentication required';
  end if;

  update public.profiles
  set phone = nullif(trim(new_phone), ''),
      updated_at = now()
  where auth_user_id = (select auth.uid());

  if not found then
    raise exception 'HRMS profile not found';
  end if;
end;
$$;

create or replace function public.clock_attendance()
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  employee text;
  existing public.attendance%rowtype;
  local_now timestamp := timezone('Asia/Manila', now());
begin
  employee := public.current_employee_code();
  if employee is null then
    raise exception 'HRMS profile not found';
  end if;

  select * into existing
  from public.attendance
  where employee_code = employee
    and work_date = local_now::date
  for update;

  if not found then
    insert into public.attendance (employee_code, work_date, clock_in, status, hours)
    values (employee, local_now::date, local_now::time, 'Present', 0);
  elsif existing.clock_out is null then
    update public.attendance
    set clock_out = local_now::time,
        hours = greatest(0, extract(epoch from (local_now::time - existing.clock_in)) / 3600),
        updated_at = now()
    where id = existing.id;
  else
    raise exception 'Attendance for today is already complete';
  end if;
end;
$$;

alter table public.profiles enable row level security;
alter table public.attendance enable row level security;
alter table public.leave_requests enable row level security;
alter table public.payroll enable row level security;
alter table public.performance_reviews enable row level security;
alter table public.announcements enable row level security;
alter table public.security_alerts enable row level security;
alter table public.account_sessions enable row level security;
alter table public.audit_logs enable row level security;

revoke all on all tables in schema public from anon, authenticated;
revoke all on all sequences in schema public from anon, authenticated;

grant select, insert, update on public.profiles to authenticated;
grant select on public.attendance to authenticated;
grant select, insert, update on public.leave_requests to authenticated;
grant select on public.payroll to authenticated;
grant select on public.performance_reviews to authenticated;
grant select, insert on public.announcements to authenticated;
grant select, update on public.security_alerts to authenticated;
grant select, delete on public.account_sessions to authenticated;
grant select on public.audit_logs to authenticated;
grant usage, select on all sequences in schema public to authenticated;

drop policy if exists profiles_select on public.profiles;
create policy profiles_select on public.profiles
  for select to authenticated
  using (
    auth_user_id = (select auth.uid())
    or (select public.is_hrms_admin())
  );

drop policy if exists profiles_insert_admin on public.profiles;
create policy profiles_insert_admin on public.profiles
  for insert to authenticated
  with check ((select public.is_hrms_admin()));

drop policy if exists profiles_update_admin on public.profiles;
create policy profiles_update_admin on public.profiles
  for update to authenticated
  using ((select public.is_hrms_admin()))
  with check ((select public.is_hrms_admin()));

drop policy if exists attendance_select on public.attendance;
create policy attendance_select on public.attendance
  for select to authenticated
  using (
    employee_code = (select public.current_employee_code())
    or (select public.is_hrms_admin())
  );

drop policy if exists leave_select on public.leave_requests;
create policy leave_select on public.leave_requests
  for select to authenticated
  using (
    employee_code = (select public.current_employee_code())
    or (select public.is_hrms_admin())
  );

drop policy if exists leave_insert_own on public.leave_requests;
create policy leave_insert_own on public.leave_requests
  for insert to authenticated
  with check (
    employee_code = (select public.current_employee_code())
    and status = 'Pending'
  );

drop policy if exists leave_update_admin on public.leave_requests;
create policy leave_update_admin on public.leave_requests
  for update to authenticated
  using ((select public.is_hrms_admin()))
  with check ((select public.is_hrms_admin()));

drop policy if exists payroll_select on public.payroll;
create policy payroll_select on public.payroll
  for select to authenticated
  using (
    employee_code = (select public.current_employee_code())
    or (select public.is_hrms_admin())
  );

drop policy if exists performance_select on public.performance_reviews;
create policy performance_select on public.performance_reviews
  for select to authenticated
  using (
    employee_code = (select public.current_employee_code())
    or (select public.is_hrms_admin())
  );

drop policy if exists announcements_select on public.announcements;
create policy announcements_select on public.announcements
  for select to authenticated
  using (true);

drop policy if exists announcements_insert_admin on public.announcements;
create policy announcements_insert_admin on public.announcements
  for insert to authenticated
  with check ((select public.is_hrms_admin()));

drop policy if exists alerts_select on public.security_alerts;
create policy alerts_select on public.security_alerts
  for select to authenticated
  using (
    employee_code = (select public.current_employee_code())
    or (select public.is_hrms_admin())
  );

drop policy if exists alerts_update_admin on public.security_alerts;
create policy alerts_update_admin on public.security_alerts
  for update to authenticated
  using ((select public.is_hrms_admin()))
  with check ((select public.is_hrms_admin()));

drop policy if exists sessions_select on public.account_sessions;
create policy sessions_select on public.account_sessions
  for select to authenticated
  using (
    employee_code = (select public.current_employee_code())
    or (select public.is_hrms_admin())
  );

drop policy if exists sessions_delete on public.account_sessions;
create policy sessions_delete on public.account_sessions
  for delete to authenticated
  using (
    is_current = false
    and (
      employee_code = (select public.current_employee_code())
      or (select public.is_hrms_admin())
    )
  );

drop policy if exists audit_select_admin on public.audit_logs;
create policy audit_select_admin on public.audit_logs
  for select to authenticated
  using ((select public.is_hrms_admin()));

revoke all on function public.current_employee_code() from public, anon;
revoke all on function public.is_hrms_admin() from public, anon;
revoke all on function public.link_auth_user_to_profile() from public, anon, authenticated;
revoke all on function public.update_own_profile(text) from public, anon;
revoke all on function public.clock_attendance() from public, anon;
grant execute on function public.current_employee_code() to authenticated;
grant execute on function public.is_hrms_admin() to authenticated;
grant execute on function public.update_own_profile(text) to authenticated;
grant execute on function public.clock_attendance() to authenticated;

insert into public.profiles
  (employee_code, first_name, last_name, email, role, department, position, status, salary, phone, hire_date)
values
  ('EMP001', 'David', 'Santos', 'employee@quantum.test', 'employee', 'Operations', 'Operations Specialist', 'Active', 38500, '+63 917 555 0142', '2024-02-12'),
  ('EMP002', 'Prince', 'Balane', 'admin@quantum.test', 'admin', 'Human Resources', 'HR Administrator', 'Active', 52000, '+63 917 555 0188', '2023-08-21'),
  ('EMP003', 'Jocielle', 'Buenavista', 'jocielle.b@quantum.test', 'employee', 'Finance', 'Payroll Associate', 'Active', 41000, '+63 917 555 0103', '2024-05-06'),
  ('EMP004', 'Harry', 'Barasona', 'harry.barasona@quantum.test', 'employee', 'Technology', 'UI Designer', 'Active', 44500, '+63 917 555 0130', '2024-01-15'),
  ('EMP005', 'Cliff', 'Bautista', 'cliff.bautista@quantum.test', 'employee', 'Technology', 'Security Analyst', 'On Leave', 47000, '+63 917 555 0167', '2023-11-20')
on conflict (employee_code) do update set
  first_name = excluded.first_name,
  last_name = excluded.last_name,
  email = excluded.email,
  role = excluded.role,
  department = excluded.department,
  position = excluded.position,
  status = excluded.status,
  salary = excluded.salary,
  phone = excluded.phone,
  hire_date = excluded.hire_date;

select setval(
  'public.employee_number_seq',
  coalesce((select max(substring(employee_code from 4)::integer) from public.profiles), 0) + 1,
  false
);

-- Link accounts that were created before this migration was run.
update public.profiles as profile
set auth_user_id = auth_user.id,
    updated_at = now()
from auth.users as auth_user
where lower(profile.email) = lower(auth_user.email)
  and profile.auth_user_id is null;

insert into public.attendance (id, employee_code, work_date, clock_in, clock_out, status, hours)
values
  (1, 'EMP001', current_date, '08:03', null, 'Present', 4.20),
  (2, 'EMP002', current_date, '07:54', null, 'Present', 4.40),
  (3, 'EMP003', current_date, '08:10', null, 'Late', 4.10),
  (4, 'EMP004', current_date - 1, '08:00', '17:06', 'Present', 8.10)
on conflict (employee_code, work_date) do update set
  clock_in = excluded.clock_in,
  clock_out = excluded.clock_out,
  status = excluded.status,
  hours = excluded.hours;

insert into public.leave_requests
  (id, employee_code, leave_type, start_date, end_date, days, reason, status)
values
  (1, 'EMP001', 'Vacation', current_date + 8, current_date + 10, 3, 'Family trip', 'Pending'),
  (2, 'EMP005', 'Sick', current_date, current_date + 1, 2, 'Medical recovery', 'Approved'),
  (3, 'EMP003', 'Emergency', current_date - 5, current_date - 5, 1, 'Family matter', 'Approved')
on conflict (id) do nothing;

insert into public.payroll (id, employee_code, period, gross, deductions, status)
values
  (1, 'EMP001', 'August 2026', 38500, 3180, 'Processed'),
  (2, 'EMP003', 'August 2026', 41000, 3460, 'Processed'),
  (3, 'EMP004', 'August 2026', 44500, 3890, 'Draft')
on conflict (employee_code, period) do update set
  gross = excluded.gross,
  deductions = excluded.deductions,
  status = excluded.status;

insert into public.performance_reviews
  (id, employee_code, period, score, goal_progress, rating)
values
  (1, 'EMP001', 'Q2 2026', 88, 82, 'Exceeds expectations'),
  (2, 'EMP003', 'Q2 2026', 91, 90, 'Outstanding'),
  (3, 'EMP004', 'Q2 2026', 86, 78, 'Exceeds expectations')
on conflict (employee_code, period) do update set
  score = excluded.score,
  goal_progress = excluded.goal_progress,
  rating = excluded.rating;

insert into public.announcements (id, title, content, priority, published_on)
values
  (1, 'Security awareness workshop', 'All staff are invited to the account-security workshop on Friday at 2:00 PM.', 'High', current_date),
  (2, 'Payroll processing complete', 'August payslips are now available in the employee portal.', 'Normal', current_date - 2)
on conflict (id) do nothing;

insert into public.security_alerts
  (alert_code, employee_code, severity, event_type, title, description, affected_label, display_time, status, recommended_action, created_at)
values
  ('SEC-1042', 'EMP004', 'Critical', 'Repeated failed logins', 'Repeated sign-in attempts blocked', 'Nine unsuccessful attempts were detected for EMP004 within five minutes.', 'Harry Barasona', '12 minutes ago', 'New', 'Verify the activity and temporarily lock the account if it was not authorized.', now() - interval '12 minutes'),
  ('SEC-1041', 'EMP002', 'High', 'New device', 'Administrator signed in from a new device', 'A new browser in Quezon City accessed an administrator account.', 'Prince Balane', '38 minutes ago', 'Investigating', 'Confirm the device with the account owner and review active sessions.', now() - interval '38 minutes'),
  ('SEC-1039', null, 'Medium', 'Data export', 'Employee report exported', 'A CSV file containing five fictional employee records was downloaded.', 'Employee directory', '2 hours ago', 'Acknowledged', 'Confirm that the export was required for an authorized HR task.', now() - interval '2 hours'),
  ('SEC-1036', 'EMP001', 'Low', 'Password change', 'Password changed successfully', 'EMP001 completed a password change from a recognized device.', 'David Santos', 'Yesterday', 'Resolved', 'No action is required unless the employee reports this activity.', now() - interval '1 day')
on conflict (alert_code) do update set
  employee_code = excluded.employee_code,
  severity = excluded.severity,
  event_type = excluded.event_type,
  title = excluded.title,
  description = excluded.description,
  affected_label = excluded.affected_label,
  display_time = excluded.display_time,
  status = excluded.status,
  recommended_action = excluded.recommended_action;

insert into public.account_sessions
  (session_code, employee_code, device, location, last_active_label, is_current)
values
  ('SES-1', 'EMP002', 'Chrome on macOS', 'Manila, PH', 'Active now', true),
  ('SES-2', 'EMP002', 'Safari on iPhone', 'Quezon City, PH', '38 minutes ago', false),
  ('SES-3', 'EMP001', 'Edge on Windows', 'Makati, PH', '1 hour ago', false)
on conflict (session_code) do update set
  employee_code = excluded.employee_code,
  device = excluded.device,
  location = excluded.location,
  last_active_label = excluded.last_active_label,
  is_current = excluded.is_current;

insert into public.audit_logs
  (id, actor_employee_code, actor_label, action, target, display_time, created_at)
values
  (1, 'EMP002', 'Prince Balane', 'Viewed security alert SEC-1041', 'Administrator account', 'Today, 10:42 AM', now()),
  (2, 'EMP003', 'Jocielle Buenavista', 'Processed payroll', 'August 2026 payroll', 'Today, 9:18 AM', now() - interval '1 hour'),
  (3, 'EMP001', 'David Santos', 'Submitted leave request', 'Vacation leave', 'Yesterday, 4:35 PM', now() - interval '1 day')
on conflict (id) do nothing;

-- Keep identity sequences ahead of the explicit fictional seed IDs.
select setval(pg_get_serial_sequence('public.attendance', 'id'), (select max(id) from public.attendance), true);
select setval(pg_get_serial_sequence('public.leave_requests', 'id'), (select max(id) from public.leave_requests), true);
select setval(pg_get_serial_sequence('public.payroll', 'id'), (select max(id) from public.payroll), true);
select setval(pg_get_serial_sequence('public.performance_reviews', 'id'), (select max(id) from public.performance_reviews), true);
select setval(pg_get_serial_sequence('public.announcements', 'id'), (select max(id) from public.announcements), true);
select setval(pg_get_serial_sequence('public.audit_logs', 'id'), (select max(id) from public.audit_logs), true);

create or replace function public.record_hrms_audit()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  actor_code text := public.current_employee_code();
  actor_name text;
  target_label text;
begin
  -- Do not turn migration/seed activity into user audit events.
  if (select auth.uid()) is null then
    if tg_op = 'DELETE' then
      return old;
    end if;
    return new;
  end if;

  select concat(first_name, ' ', last_name)
  into actor_name
  from public.profiles
  where employee_code = actor_code;

  target_label := case tg_table_name
    when 'profiles' then coalesce(new.employee_code, old.employee_code)
    when 'attendance' then coalesce(new.employee_code, old.employee_code)
    when 'leave_requests' then 'Leave request ' || coalesce(new.id, old.id)::text
    when 'announcements' then coalesce(new.title, old.title)
    when 'security_alerts' then coalesce(new.alert_code, old.alert_code)
    when 'account_sessions' then coalesce(new.session_code, old.session_code)
    else tg_table_name
  end;

  insert into public.audit_logs
    (actor_employee_code, actor_label, action, target, display_time)
  values
    (
      actor_code,
      coalesce(actor_name, 'Authenticated user'),
      initcap(lower(tg_op)) || ' ' || replace(tg_table_name, '_', ' '),
      target_label,
      to_char(timezone('Asia/Manila', now()), 'Mon DD, YYYY HH12:MI AM')
    );

  if tg_op = 'DELETE' then
    return old;
  end if;
  return new;
end;
$$;

drop trigger if exists audit_profiles on public.profiles;
create trigger audit_profiles after insert or update on public.profiles
  for each row execute procedure public.record_hrms_audit();

drop trigger if exists audit_attendance on public.attendance;
create trigger audit_attendance after insert or update on public.attendance
  for each row execute procedure public.record_hrms_audit();

drop trigger if exists audit_leave_requests on public.leave_requests;
create trigger audit_leave_requests after insert or update on public.leave_requests
  for each row execute procedure public.record_hrms_audit();

drop trigger if exists audit_announcements on public.announcements;
create trigger audit_announcements after insert on public.announcements
  for each row execute procedure public.record_hrms_audit();

drop trigger if exists audit_security_alerts on public.security_alerts;
create trigger audit_security_alerts after update on public.security_alerts
  for each row execute procedure public.record_hrms_audit();

drop trigger if exists audit_account_sessions on public.account_sessions;
create trigger audit_account_sessions after delete on public.account_sessions
  for each row execute procedure public.record_hrms_audit();

revoke all on function public.record_hrms_audit() from public, anon, authenticated;
