-- Quantum HRMS premium operations layer.
-- This migration keeps employee and administrator workflows in Supabase,
-- applies least-privilege RLS, and connects every decision to an audit trail.

-- ---------------------------------------------------------------------------
-- Roles and reusable authorization helpers
-- ---------------------------------------------------------------------------

alter table public.profiles drop constraint if exists profiles_role_check;
alter table public.profiles
  add constraint profiles_role_check
  check (role in ('employee', 'admin', 'hr_admin', 'payroll_admin', 'security_admin', 'auditor'));

create or replace function public.current_hrms_role()
returns text
language sql
stable
security definer
set search_path = ''
as $$
  select role
  from public.profiles
  where auth_user_id = (select auth.uid())
    and status = 'Active'
  limit 1
$$;

create or replace function public.has_hrms_role(allowed_roles text[])
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select coalesce(public.current_hrms_role() = any(allowed_roles), false)
$$;

create or replace function public.is_hrms_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select public.has_hrms_role(array['admin', 'hr_admin', 'payroll_admin', 'security_admin'])
$$;

create or replace function public.is_active_hrms_user()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.profiles
    where auth_user_id = (select auth.uid())
      and status in ('Active', 'On Leave')
  )
$$;

-- ---------------------------------------------------------------------------
-- Shared employee request and communication records
-- ---------------------------------------------------------------------------

create table if not exists public.employee_requests (
  id bigint generated by default as identity primary key,
  employee_code text not null references public.profiles(employee_code),
  request_type text not null check (request_type in (
    'Attendance Correction', 'Overtime', 'Schedule Change', 'Profile Correction',
    'Document Request', 'Payroll Concern', 'General HR'
  )),
  subject text not null check (char_length(subject) between 3 and 120),
  description text not null check (char_length(description) between 3 and 1000),
  requested_date date,
  requested_value text check (requested_value is null or char_length(requested_value) <= 500),
  priority text not null default 'Normal' check (priority in ('Normal', 'High', 'Urgent')),
  status text not null default 'Submitted' check (status in (
    'Submitted', 'Under Review', 'More Information', 'Approved', 'Rejected',
    'Completed', 'Cancelled'
  )),
  assigned_to text references public.profiles(employee_code),
  decision_note text,
  reviewed_by text references public.profiles(employee_code),
  reviewed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists employee_requests_employee_idx
  on public.employee_requests (employee_code, created_at desc);
create index if not exists employee_requests_queue_idx
  on public.employee_requests (status, priority, created_at);

create table if not exists public.request_comments (
  id bigint generated by default as identity primary key,
  request_id bigint not null references public.employee_requests(id) on delete cascade,
  author_employee_code text not null references public.profiles(employee_code),
  body text not null check (char_length(body) between 1 and 1000),
  is_internal boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists request_comments_request_idx
  on public.request_comments (request_id, created_at);

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  employee_code text not null references public.profiles(employee_code) on delete cascade,
  category text not null default 'HR',
  title text not null check (char_length(title) between 3 and 120),
  message text not null check (char_length(message) between 3 and 600),
  destination text,
  action_label text,
  read_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists notifications_employee_idx
  on public.notifications (employee_code, read_at, created_at desc);

-- ---------------------------------------------------------------------------
-- Documents, schedules, total rewards, and growth
-- ---------------------------------------------------------------------------

create table if not exists public.employee_documents (
  id bigint generated by default as identity primary key,
  employee_code text references public.profiles(employee_code) on delete cascade,
  title text not null check (char_length(title) between 3 and 160),
  document_type text not null check (document_type in (
    'Policy', 'Payslip', 'Certificate', 'Contract', 'Memo', 'Tax', 'Other'
  )),
  period text,
  content text not null check (char_length(content) between 3 and 10000),
  filename text not null,
  version text not null default '1.0',
  requires_ack boolean not null default false,
  sensitive boolean not null default false,
  expires_on date,
  uploaded_by text references public.profiles(employee_code),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists employee_documents_visibility_idx
  on public.employee_documents (employee_code, document_type, created_at desc);

create table if not exists public.document_acknowledgements (
  id bigint generated by default as identity primary key,
  document_id bigint not null references public.employee_documents(id) on delete cascade,
  employee_code text not null references public.profiles(employee_code) on delete cascade,
  acknowledged_at timestamptz not null default now(),
  unique (document_id, employee_code)
);

create table if not exists public.work_schedules (
  id bigint generated by default as identity primary key,
  employee_code text not null references public.profiles(employee_code) on delete cascade,
  work_date date not null,
  shift_start time not null,
  shift_end time not null,
  location text not null default 'Main Office',
  work_mode text not null default 'On-site' check (work_mode in ('On-site', 'Remote', 'Hybrid', 'Rest Day')),
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (employee_code, work_date),
  check (work_mode = 'Rest Day' or shift_end > shift_start)
);

create index if not exists work_schedules_employee_date_idx
  on public.work_schedules (employee_code, work_date);

create table if not exists public.employee_benefits (
  id bigint generated by default as identity primary key,
  employee_code text not null references public.profiles(employee_code) on delete cascade,
  benefit_type text not null,
  provider text,
  plan_name text not null,
  employee_share numeric(12, 2) not null default 0 check (employee_share >= 0),
  employer_share numeric(12, 2) not null default 0 check (employer_share >= 0),
  status text not null default 'Active' check (status in ('Active', 'Pending', 'Inactive')),
  effective_date date not null default current_date,
  created_at timestamptz not null default now(),
  unique (employee_code, benefit_type, plan_name)
);

create table if not exists public.employee_goals (
  id bigint generated by default as identity primary key,
  employee_code text not null references public.profiles(employee_code) on delete cascade,
  title text not null check (char_length(title) between 3 and 160),
  description text not null default '',
  category text not null default 'Role',
  progress integer not null default 0 check (progress between 0 and 100),
  status text not null default 'Active' check (status in ('Draft', 'Active', 'At Risk', 'Completed', 'Archived')),
  due_date date,
  created_by text references public.profiles(employee_code),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists employee_goals_employee_idx
  on public.employee_goals (employee_code, status, due_date);

-- ---------------------------------------------------------------------------
-- Onboarding/offboarding, payroll runs, and performance cycles
-- ---------------------------------------------------------------------------

create table if not exists public.lifecycle_cases (
  id bigint generated by default as identity primary key,
  employee_code text not null references public.profiles(employee_code),
  case_type text not null check (case_type in ('Onboarding', 'Offboarding')),
  status text not null default 'Active' check (status in ('Draft', 'Active', 'Completed', 'Cancelled')),
  target_date date not null,
  owner_code text references public.profiles(employee_code),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists lifecycle_open_case_idx
  on public.lifecycle_cases (employee_code, case_type)
  where status in ('Draft', 'Active');

create table if not exists public.lifecycle_tasks (
  id bigint generated by default as identity primary key,
  case_id bigint not null references public.lifecycle_cases(id) on delete cascade,
  title text not null,
  category text not null,
  status text not null default 'Pending' check (status in ('Pending', 'Complete', 'Skipped')),
  employee_visible boolean not null default true,
  completed_by text references public.profiles(employee_code),
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists lifecycle_tasks_case_idx
  on public.lifecycle_tasks (case_id, status);

create table if not exists public.payroll_runs (
  id bigint generated by default as identity primary key,
  period text not null unique check (char_length(period) between 3 and 60),
  deduction_rate numeric(5, 2) not null default 0 check (deduction_rate between 0 and 50),
  status text not null default 'Draft' check (status in (
    'Draft', 'Validation', 'Approved', 'Released', 'Paid', 'Locked'
  )),
  employee_count integer not null default 0,
  gross_total numeric(14, 2) not null default 0,
  net_total numeric(14, 2) not null default 0,
  created_by text references public.profiles(employee_code),
  approved_by text references public.profiles(employee_code),
  approved_at timestamptz,
  released_at timestamptz,
  paid_at timestamptz,
  locked_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.payroll
  add column if not exists payroll_run_id bigint references public.payroll_runs(id),
  add column if not exists allowances numeric(12, 2) not null default 0 check (allowances >= 0),
  add column if not exists bonuses numeric(12, 2) not null default 0 check (bonuses >= 0);

alter table public.payroll drop constraint if exists payroll_status_check;
update public.payroll set status = 'Released' where status = 'Processed';
alter table public.payroll
  add constraint payroll_status_check
  check (status in ('Draft', 'Validation', 'Approved', 'Released', 'Paid', 'Locked'));

-- Recalculate net pay to include explicit rewards components.
alter table public.payroll drop column if exists net;
alter table public.payroll
  add column net numeric(12, 2)
  generated always as (gross + allowances + bonuses - deductions) stored;

create index if not exists payroll_run_idx on public.payroll (payroll_run_id);

create table if not exists public.performance_cycles (
  id bigint generated by default as identity primary key,
  title text not null,
  period text not null unique,
  status text not null default 'Draft' check (status in ('Draft', 'Active', 'Review', 'Closed')),
  start_date date,
  end_date date,
  created_by text references public.profiles(employee_code),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (end_date is null or start_date is null or end_date >= start_date)
);

alter table public.performance_reviews
  add column if not exists cycle_id bigint references public.performance_cycles(id),
  add column if not exists status text not null default 'Published',
  add column if not exists published_at timestamptz;

alter table public.performance_reviews drop constraint if exists performance_reviews_status_check;
alter table public.performance_reviews
  add constraint performance_reviews_status_check
  check (status in ('Draft', 'Published'));
update public.performance_reviews
set status = 'Published', published_at = coalesce(published_at, created_at);
alter table public.performance_reviews alter column status set default 'Draft';

-- Keep timestamps consistent across administrator and employee mutations.
create or replace function public.set_hrms_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

do $$
declare
  target_table text;
begin
  foreach target_table in array array[
    'employee_requests', 'employee_documents', 'work_schedules', 'employee_goals',
    'lifecycle_cases', 'lifecycle_tasks', 'payroll_runs', 'performance_cycles'
  ]
  loop
    execute format('drop trigger if exists set_updated_at on public.%I', target_table);
    execute format(
      'create trigger set_updated_at before update on public.%I for each row execute procedure public.set_hrms_updated_at()',
      target_table
    );
  end loop;
end $$;

-- ---------------------------------------------------------------------------
-- Row-Level Security: employees see only their own records; specialist roles
-- receive only the modules needed for their work.
-- ---------------------------------------------------------------------------

alter table public.employee_requests enable row level security;
alter table public.request_comments enable row level security;
alter table public.notifications enable row level security;
alter table public.employee_documents enable row level security;
alter table public.document_acknowledgements enable row level security;
alter table public.work_schedules enable row level security;
alter table public.employee_benefits enable row level security;
alter table public.employee_goals enable row level security;
alter table public.lifecycle_cases enable row level security;
alter table public.lifecycle_tasks enable row level security;
alter table public.payroll_runs enable row level security;
alter table public.performance_cycles enable row level security;

-- Replace the earlier broad policies so the new specialist roles stay scoped.
do $$
declare
  policy_record record;
begin
  for policy_record in
    select schemaname, tablename, policyname
    from pg_policies
    where schemaname = 'public'
      and tablename = any(array[
        'profiles', 'attendance', 'leave_requests', 'payroll', 'performance_reviews',
        'announcements', 'security_alerts', 'account_sessions', 'audit_logs',
        'employee_requests', 'request_comments', 'notifications',
        'employee_documents', 'document_acknowledgements', 'work_schedules',
        'employee_benefits', 'employee_goals', 'lifecycle_cases',
        'lifecycle_tasks', 'payroll_runs', 'performance_cycles'
      ])
  loop
    execute format(
      'drop policy if exists %I on %I.%I',
      policy_record.policyname,
      policy_record.schemaname,
      policy_record.tablename
    );
  end loop;
end $$;

create policy profiles_select on public.profiles
  for select to authenticated
  using (
    (auth_user_id = (select auth.uid()) and status in ('Active', 'On Leave'))
    or public.has_hrms_role(array['admin', 'hr_admin', 'payroll_admin', 'auditor'])
  );

create policy profiles_update_hr on public.profiles
  for update to authenticated
  using (public.has_hrms_role(array['admin', 'hr_admin']))
  with check (public.has_hrms_role(array['admin', 'hr_admin']));

create policy attendance_select on public.attendance
  for select to authenticated
  using (
    (employee_code = public.current_employee_code() and public.is_active_hrms_user())
    or public.has_hrms_role(array['admin', 'hr_admin', 'payroll_admin', 'auditor'])
  );

create policy leave_select on public.leave_requests
  for select to authenticated
  using (
    (employee_code = public.current_employee_code() and public.is_active_hrms_user())
    or public.has_hrms_role(array['admin', 'hr_admin', 'auditor'])
  );

create policy payroll_select on public.payroll
  for select to authenticated
  using (
    (
      employee_code = public.current_employee_code()
      and status in ('Released', 'Paid', 'Locked')
      and public.is_active_hrms_user()
    )
    or public.has_hrms_role(array['admin', 'payroll_admin', 'auditor'])
  );

create policy performance_select on public.performance_reviews
  for select to authenticated
  using (
    (
      employee_code = public.current_employee_code()
      and status = 'Published'
      and public.is_active_hrms_user()
    )
    or public.has_hrms_role(array['admin', 'hr_admin', 'auditor'])
  );

create policy announcements_select on public.announcements
  for select to authenticated
  using (public.is_active_hrms_user());

create policy announcements_insert_hr on public.announcements
  for insert to authenticated
  with check (public.has_hrms_role(array['admin', 'hr_admin']));

create policy alerts_select on public.security_alerts
  for select to authenticated
  using (
    (employee_code = public.current_employee_code() and public.is_active_hrms_user())
    or public.has_hrms_role(array['admin', 'security_admin', 'auditor'])
  );

create policy alerts_update_security on public.security_alerts
  for update to authenticated
  using (public.has_hrms_role(array['admin', 'security_admin']))
  with check (public.has_hrms_role(array['admin', 'security_admin']));

create policy sessions_select on public.account_sessions
  for select to authenticated
  using (
    (employee_code = public.current_employee_code() and public.is_active_hrms_user())
    or public.has_hrms_role(array['admin', 'security_admin'])
  );

create policy sessions_delete on public.account_sessions
  for delete to authenticated
  using (
    is_current = false
    and (
      employee_code = public.current_employee_code()
      or public.has_hrms_role(array['admin', 'security_admin'])
    )
  );

create policy audit_select on public.audit_logs
  for select to authenticated
  using (public.has_hrms_role(array['admin', 'hr_admin', 'security_admin', 'auditor']));

create policy requests_select on public.employee_requests
  for select to authenticated
  using (
    (employee_code = public.current_employee_code() and public.is_active_hrms_user())
    or public.has_hrms_role(array['admin', 'hr_admin', 'auditor'])
    or (
      request_type = 'Payroll Concern'
      and public.has_hrms_role(array['payroll_admin'])
    )
  );

create policy request_comments_select on public.request_comments
  for select to authenticated
  using (
    exists (
      select 1
      from public.employee_requests request
      where request.id = request_comments.request_id
        and request.employee_code = public.current_employee_code()
        and request_comments.is_internal = false
        and public.is_active_hrms_user()
    )
    or public.has_hrms_role(array['admin', 'hr_admin', 'auditor'])
    or (
      exists (
        select 1
        from public.employee_requests request
        where request.id = request_comments.request_id
          and request.request_type = 'Payroll Concern'
      )
      and public.has_hrms_role(array['payroll_admin'])
    )
  );

create policy notifications_select on public.notifications
  for select to authenticated
  using (
    (employee_code = public.current_employee_code() and public.is_active_hrms_user())
    or public.has_hrms_role(array['admin', 'hr_admin', 'auditor'])
  );

create policy documents_select on public.employee_documents
  for select to authenticated
  using (
    (
      (employee_code is null or employee_code = public.current_employee_code())
      and public.is_active_hrms_user()
    )
    or public.has_hrms_role(array['admin', 'hr_admin', 'auditor'])
    or (
      document_type in ('Payslip', 'Tax')
      and public.has_hrms_role(array['payroll_admin'])
    )
  );

create policy documents_insert_hr on public.employee_documents
  for insert to authenticated
  with check (
    public.has_hrms_role(array['admin', 'hr_admin'])
    or (
      document_type in ('Payslip', 'Tax')
      and employee_code is not null
      and public.has_hrms_role(array['payroll_admin'])
    )
  );

create policy documents_update_hr on public.employee_documents
  for update to authenticated
  using (
    public.has_hrms_role(array['admin', 'hr_admin'])
    or (document_type in ('Payslip', 'Tax') and public.has_hrms_role(array['payroll_admin']))
  )
  with check (
    public.has_hrms_role(array['admin', 'hr_admin'])
    or (
      document_type in ('Payslip', 'Tax')
      and employee_code is not null
      and public.has_hrms_role(array['payroll_admin'])
    )
  );

create policy acknowledgements_select on public.document_acknowledgements
  for select to authenticated
  using (
    (employee_code = public.current_employee_code() and public.is_active_hrms_user())
    or public.has_hrms_role(array['admin', 'hr_admin', 'auditor'])
  );

create policy schedules_select on public.work_schedules
  for select to authenticated
  using (
    (employee_code = public.current_employee_code() and public.is_active_hrms_user())
    or public.has_hrms_role(array['admin', 'hr_admin', 'auditor'])
  );

create policy schedules_write_hr on public.work_schedules
  for all to authenticated
  using (public.has_hrms_role(array['admin', 'hr_admin']))
  with check (public.has_hrms_role(array['admin', 'hr_admin']));

create policy benefits_select on public.employee_benefits
  for select to authenticated
  using (
    (employee_code = public.current_employee_code() and public.is_active_hrms_user())
    or public.has_hrms_role(array['admin', 'hr_admin', 'payroll_admin', 'auditor'])
  );

create policy benefits_write_admin on public.employee_benefits
  for all to authenticated
  using (public.has_hrms_role(array['admin', 'hr_admin', 'payroll_admin']))
  with check (public.has_hrms_role(array['admin', 'hr_admin', 'payroll_admin']));

create policy goals_select on public.employee_goals
  for select to authenticated
  using (
    (employee_code = public.current_employee_code() and public.is_active_hrms_user())
    or public.has_hrms_role(array['admin', 'hr_admin', 'auditor'])
  );

create policy goals_write_hr on public.employee_goals
  for all to authenticated
  using (public.has_hrms_role(array['admin', 'hr_admin']))
  with check (public.has_hrms_role(array['admin', 'hr_admin']));

create policy lifecycle_cases_select on public.lifecycle_cases
  for select to authenticated
  using (
    (employee_code = public.current_employee_code() and public.is_active_hrms_user())
    or public.has_hrms_role(array['admin', 'hr_admin', 'auditor'])
  );

create policy lifecycle_tasks_select on public.lifecycle_tasks
  for select to authenticated
  using (
    (
      employee_visible = true
      and exists (
        select 1
        from public.lifecycle_cases lifecycle_case
        where lifecycle_case.id = lifecycle_tasks.case_id
          and lifecycle_case.employee_code = public.current_employee_code()
      )
      and public.is_active_hrms_user()
    )
    or public.has_hrms_role(array['admin', 'hr_admin', 'auditor'])
  );

create policy payroll_runs_select on public.payroll_runs
  for select to authenticated
  using (public.has_hrms_role(array['admin', 'payroll_admin', 'auditor']));

create policy performance_cycles_select on public.performance_cycles
  for select to authenticated
  using (
    (status <> 'Draft' and public.is_active_hrms_user())
    or public.has_hrms_role(array['admin', 'hr_admin', 'auditor'])
  );

create policy performance_cycles_write_hr on public.performance_cycles
  for all to authenticated
  using (public.has_hrms_role(array['admin', 'hr_admin']))
  with check (public.has_hrms_role(array['admin', 'hr_admin']));

-- ---------------------------------------------------------------------------
-- Employee-facing workflows. Security-definer RPCs validate ownership and
-- never trust an employee code supplied by the browser.
-- ---------------------------------------------------------------------------

create or replace function public.notify_employee(
  target_employee text,
  notification_category text,
  notification_title text,
  notification_message text,
  notification_destination text default null,
  notification_action text default null
)
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
  notification_id bigint;
begin
  insert into public.notifications
    (employee_code, category, title, message, destination, action_label)
  values
    (
      target_employee,
      trim(notification_category),
      trim(notification_title),
      trim(notification_message),
      nullif(trim(notification_destination), ''),
      nullif(trim(notification_action), '')
    )
  returning id into notification_id;
  return notification_id;
end;
$$;

create or replace function public.submit_employee_request(
  requested_type text,
  requested_subject text,
  requested_description text,
  requested_date date default null,
  requested_value text default null,
  requested_priority text default 'Normal'
)
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
  employee text := public.current_employee_code();
  new_id bigint;
begin
  if employee is null or not public.is_active_hrms_user() then
    raise exception 'Active authentication is required';
  end if;
  if requested_type not in (
    'Attendance Correction', 'Overtime', 'Schedule Change', 'Profile Correction',
    'Document Request', 'Payroll Concern', 'General HR'
  ) then
    raise exception 'Unsupported request type';
  end if;
  if char_length(trim(requested_subject)) not between 3 and 120 then
    raise exception 'Use a subject between 3 and 120 characters';
  end if;
  if char_length(trim(requested_description)) not between 3 and 1000 then
    raise exception 'Use a description between 3 and 1000 characters';
  end if;
  if requested_priority not in ('Normal', 'High', 'Urgent') then
    raise exception 'Unsupported request priority';
  end if;

  insert into public.employee_requests
    (employee_code, request_type, subject, description, requested_date, requested_value, priority)
  values
    (
      employee,
      requested_type,
      trim(requested_subject),
      trim(requested_description),
      requested_date,
      nullif(trim(requested_value), ''),
      requested_priority
    )
  returning id into new_id;

  return new_id;
end;
$$;

create or replace function public.add_request_comment(
  selected_request_id bigint,
  comment_body text,
  internal_note boolean default false
)
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
  employee text := public.current_employee_code();
  request_owner text;
  request_kind text;
  comment_id bigint;
  can_manage boolean := public.has_hrms_role(array['admin', 'hr_admin', 'payroll_admin']);
begin
  if employee is null or not public.is_active_hrms_user() then
    raise exception 'Active authentication is required';
  end if;
  if char_length(trim(comment_body)) not between 1 and 1000 then
    raise exception 'Use a comment between 1 and 1000 characters';
  end if;

  select employee_code, request_type into request_owner, request_kind
  from public.employee_requests
  where id = selected_request_id;

  if request_owner is null or (request_owner <> employee and not can_manage) then
    raise exception 'Request not found';
  end if;
  if public.current_hrms_role() = 'payroll_admin' and request_kind <> 'Payroll Concern' then
    raise exception 'Payroll administrators may respond only to payroll concerns';
  end if;
  if internal_note and not can_manage then
    raise exception 'Only an authorized administrator can add an internal note';
  end if;

  insert into public.request_comments
    (request_id, author_employee_code, body, is_internal)
  values
    (selected_request_id, employee, trim(comment_body), internal_note)
  returning id into comment_id;

  update public.employee_requests
  set status = case
        when request_owner = employee and status = 'More Information' then 'Submitted'
        else status
      end,
      updated_at = now()
  where id = selected_request_id;

  if can_manage and not internal_note and request_owner <> employee then
    perform public.notify_employee(
      request_owner,
      'Request',
      'New response on your request',
      'HR added a response to request #' || selected_request_id::text || '.',
      'requests',
      'View request'
    );
  end if;

  return comment_id;
end;
$$;

create or replace function public.cancel_employee_request(selected_request_id bigint)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  if not public.is_active_hrms_user() then
    raise exception 'Active authentication is required';
  end if;

  update public.employee_requests
  set status = 'Cancelled', updated_at = now()
  where id = selected_request_id
    and employee_code = public.current_employee_code()
    and status in ('Submitted', 'More Information');

  if not found then
    raise exception 'This request can no longer be cancelled';
  end if;
end;
$$;

create or replace function public.review_employee_request(
  selected_request_id bigint,
  decision text,
  decision_reason text
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  request_owner text;
  request_subject text;
begin
  if not public.has_hrms_role(array['admin', 'hr_admin', 'payroll_admin']) then
    raise exception 'HR administrator access required';
  end if;
  if decision not in ('Under Review', 'More Information', 'Approved', 'Rejected', 'Completed') then
    raise exception 'Unsupported request decision';
  end if;
  if decision in ('More Information', 'Rejected')
     and char_length(trim(decision_reason)) < 3 then
    raise exception 'Explain what the employee needs to do or why the request was rejected';
  end if;
  if public.current_hrms_role() = 'payroll_admin'
     and not exists (
       select 1 from public.employee_requests
       where id = selected_request_id and request_type = 'Payroll Concern'
     ) then
    raise exception 'Payroll administrators may review only payroll concerns';
  end if;

  update public.employee_requests
  set status = decision,
      decision_note = nullif(trim(decision_reason), ''),
      assigned_to = coalesce(assigned_to, public.current_employee_code()),
      reviewed_by = public.current_employee_code(),
      reviewed_at = now(),
      updated_at = now()
  where id = selected_request_id
    and status not in ('Cancelled', 'Completed')
  returning employee_code, subject into request_owner, request_subject;

  if request_owner is null then
    raise exception 'Open request not found';
  end if;

  perform public.notify_employee(
    request_owner,
    'Request',
    'Request ' || lower(decision),
    request_subject || ' is now ' || decision || case
      when nullif(trim(decision_reason), '') is not null then ': ' || trim(decision_reason)
      else '.'
    end,
    'requests',
    'View request'
  );
end;
$$;

create or replace function public.mark_notification_read(selected_notification_id bigint)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  update public.notifications
  set read_at = coalesce(read_at, now())
  where id = selected_notification_id
    and employee_code = public.current_employee_code();
  if not found then raise exception 'Notification not found'; end if;
end;
$$;

create or replace function public.mark_all_notifications_read()
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  if not public.is_active_hrms_user() then raise exception 'Active authentication is required'; end if;
  update public.notifications
  set read_at = now()
  where employee_code = public.current_employee_code()
    and read_at is null;
end;
$$;

create or replace function public.acknowledge_document(selected_document_id bigint)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  employee text := public.current_employee_code();
begin
  if employee is null or not public.is_active_hrms_user() then
    raise exception 'Active authentication is required';
  end if;
  if not exists (
    select 1
    from public.employee_documents document
    where document.id = selected_document_id
      and (document.employee_code is null or document.employee_code = employee)
      and document.requires_ack = true
  ) then
    raise exception 'Acknowledgement is not available for this document';
  end if;

  insert into public.document_acknowledgements (document_id, employee_code)
  values (selected_document_id, employee)
  on conflict (document_id, employee_code) do update
    set acknowledged_at = excluded.acknowledged_at;
end;
$$;

create or replace function public.update_goal_progress(
  selected_goal_id bigint,
  new_progress integer
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  if new_progress < 0 or new_progress > 100 then
    raise exception 'Progress must be between 0 and 100';
  end if;

  update public.employee_goals
  set progress = new_progress,
      status = case when new_progress = 100 then 'Completed' else 'Active' end,
      updated_at = now()
  where id = selected_goal_id
    and (
      employee_code = public.current_employee_code()
      or public.has_hrms_role(array['admin', 'hr_admin'])
    );

  if not found then raise exception 'Goal not found'; end if;
end;
$$;

-- ---------------------------------------------------------------------------
-- Administrator workflows with explicit, database-enforced state changes
-- ---------------------------------------------------------------------------

create or replace function public.review_leave_request(request_id bigint, decision text)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  request_owner text;
  request_type text;
begin
  if not public.has_hrms_role(array['admin', 'hr_admin']) then
    raise exception 'HR administrator access required';
  end if;
  if decision not in ('Approved', 'Rejected') then
    raise exception 'Decision must be Approved or Rejected';
  end if;

  update public.leave_requests
  set status = decision,
      reviewed_by = public.current_employee_code(),
      reviewed_at = now()
  where id = request_id
    and status = 'Pending'
  returning employee_code, leave_type into request_owner, request_type;

  if request_owner is null then
    raise exception 'Pending leave request not found';
  end if;

  perform public.notify_employee(
    request_owner,
    'Leave',
    request_type || ' leave ' || lower(decision),
    'Your leave request has been ' || lower(decision) || '.',
    'leave',
    'View leave'
  );
end;
$$;

create or replace function public.create_lifecycle_case(
  target_employee text,
  selected_case_type text,
  selected_target_date date
)
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
  new_case_id bigint;
begin
  if not public.has_hrms_role(array['admin', 'hr_admin']) then
    raise exception 'HR administrator access required';
  end if;
  if selected_case_type not in ('Onboarding', 'Offboarding') then
    raise exception 'Unsupported lifecycle case type';
  end if;
  if selected_target_date is null then
    raise exception 'A target date is required';
  end if;
  if not exists (select 1 from public.profiles where employee_code = target_employee) then
    raise exception 'Employee not found';
  end if;

  insert into public.lifecycle_cases
    (employee_code, case_type, status, target_date, owner_code)
  values
    (target_employee, selected_case_type, 'Active', selected_target_date, public.current_employee_code())
  returning id into new_case_id;

  if selected_case_type = 'Onboarding' then
    insert into public.lifecycle_tasks (case_id, title, category, employee_visible)
    values
      (new_case_id, 'Confirm employee profile and emergency contact', 'People', true),
      (new_case_id, 'Provision least-privilege HRMS access', 'Access', false),
      (new_case_id, 'Acknowledge company policies', 'Compliance', true),
      (new_case_id, 'Complete first-week orientation', 'Experience', true);
  else
    insert into public.lifecycle_tasks (case_id, title, category, employee_visible)
    values
      (new_case_id, 'Confirm final working date and turnover', 'People', true),
      (new_case_id, 'Return company assets', 'Assets', true),
      (new_case_id, 'Complete final payroll validation', 'Payroll', false),
      (new_case_id, 'Deactivate HRMS access after clearance', 'Access', false);
  end if;

  perform public.notify_employee(
    target_employee,
    'Lifecycle',
    selected_case_type || ' checklist started',
    'A secure ' || lower(selected_case_type) || ' checklist is now available.',
    'journey',
    'View checklist'
  );

  return new_case_id;
end;
$$;

create or replace function public.update_lifecycle_task(
  selected_task_id bigint,
  new_status text
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  parent_case_id bigint;
  parent_employee text;
  parent_type text;
  remaining_tasks integer;
begin
  if not public.has_hrms_role(array['admin', 'hr_admin']) then
    raise exception 'HR administrator access required';
  end if;
  if new_status not in ('Pending', 'Complete', 'Skipped') then
    raise exception 'Unsupported task status';
  end if;

  update public.lifecycle_tasks
  set status = new_status,
      completed_by = case when new_status in ('Complete', 'Skipped') then public.current_employee_code() else null end,
      completed_at = case when new_status in ('Complete', 'Skipped') then now() else null end,
      updated_at = now()
  where id = selected_task_id
  returning case_id into parent_case_id;

  if parent_case_id is null then raise exception 'Lifecycle task not found'; end if;

  select employee_code, case_type into parent_employee, parent_type
  from public.lifecycle_cases
  where id = parent_case_id;

  select count(*) into remaining_tasks
  from public.lifecycle_tasks
  where case_id = parent_case_id
    and status = 'Pending';

  if remaining_tasks = 0 then
    update public.lifecycle_cases
    set status = 'Completed', updated_at = now()
    where id = parent_case_id;

    if parent_type = 'Offboarding' then
      update public.profiles
      set status = 'Inactive', updated_at = now()
      where employee_code = parent_employee;
    end if;
  end if;
end;
$$;

create or replace function public.generate_payroll(payroll_period text, deduction_rate numeric)
returns integer
language plpgsql
security definer
set search_path = ''
as $$
declare
  run_id bigint;
  affected integer;
begin
  if not public.has_hrms_role(array['admin', 'payroll_admin']) then
    raise exception 'Payroll administrator access required';
  end if;
  if char_length(trim(payroll_period)) not between 3 and 60 then
    raise exception 'Enter a valid payroll period';
  end if;
  if deduction_rate < 0 or deduction_rate > 50 then
    raise exception 'Deduction rate must be between 0 and 50 percent';
  end if;
  if exists (
    select 1 from public.payroll_runs
    where period = trim(payroll_period) and status = 'Locked'
  ) then
    raise exception 'A locked payroll run cannot be regenerated';
  end if;

  insert into public.payroll_runs
    (period, deduction_rate, status, created_by)
  values
    (trim(payroll_period), deduction_rate, 'Draft', public.current_employee_code())
  on conflict (period) do update set
    deduction_rate = excluded.deduction_rate,
    status = 'Draft',
    approved_by = null,
    approved_at = null,
    released_at = null,
    paid_at = null,
    locked_at = null,
    updated_at = now()
  returning id into run_id;

  insert into public.payroll
    (employee_code, payroll_run_id, period, gross, allowances, bonuses, deductions, status, payment_date)
  select
    employee_code,
    run_id,
    trim(payroll_period),
    salary,
    0,
    0,
    round(salary * (deduction_rate / 100), 2),
    'Draft',
    null
  from public.profiles
  where status in ('Active', 'On Leave')
    and role = 'employee'
  on conflict (employee_code, period) do update set
    payroll_run_id = excluded.payroll_run_id,
    gross = excluded.gross,
    allowances = excluded.allowances,
    bonuses = excluded.bonuses,
    deductions = excluded.deductions,
    status = 'Draft',
    payment_date = null;

  get diagnostics affected = row_count;

  update public.payroll_runs payroll_run
  set employee_count = totals.employee_count,
      gross_total = totals.gross_total,
      net_total = totals.net_total,
      updated_at = now()
  from (
    select count(*)::integer employee_count,
           coalesce(sum(gross + allowances + bonuses), 0) gross_total,
           coalesce(sum(net), 0) net_total
    from public.payroll
    where payroll_run_id = run_id
  ) totals
  where payroll_run.id = run_id;

  return affected;
end;
$$;

create or replace function public.transition_payroll_run(
  selected_run_id bigint,
  next_status text
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  current_status text;
  run_period text;
  employee_record record;
begin
  if not public.has_hrms_role(array['admin', 'payroll_admin']) then
    raise exception 'Payroll administrator access required';
  end if;

  select status, period into current_status, run_period
  from public.payroll_runs
  where id = selected_run_id
  for update;

  if current_status is null then raise exception 'Payroll run not found'; end if;
  if not (
    (current_status = 'Draft' and next_status = 'Validation')
    or (current_status = 'Validation' and next_status = 'Approved')
    or (current_status = 'Approved' and next_status = 'Released')
    or (current_status = 'Released' and next_status = 'Paid')
    or (current_status = 'Paid' and next_status = 'Locked')
  ) then
    raise exception 'Payroll must advance through Draft, Validation, Approved, Released, Paid, and Locked';
  end if;

  update public.payroll_runs
  set status = next_status,
      approved_by = case when next_status = 'Approved' then public.current_employee_code() else approved_by end,
      approved_at = case when next_status = 'Approved' then now() else approved_at end,
      released_at = case when next_status = 'Released' then now() else released_at end,
      paid_at = case when next_status = 'Paid' then now() else paid_at end,
      locked_at = case when next_status = 'Locked' then now() else locked_at end,
      updated_at = now()
  where id = selected_run_id;

  update public.payroll
  set status = next_status,
      payment_date = case when next_status = 'Paid' then current_date else payment_date end
  where payroll_run_id = selected_run_id;

  if next_status = 'Released' then
    for employee_record in
      select employee_code from public.payroll where payroll_run_id = selected_run_id
    loop
      perform public.notify_employee(
        employee_record.employee_code,
        'Payroll',
        'Payslip released',
        'Your private payslip for ' || run_period || ' is ready.',
        'pay',
        'View payslip'
      );
    end loop;
  end if;
end;
$$;

create or replace function public.save_performance_review(
  target_employee text,
  review_period text,
  review_score integer,
  review_goal_progress integer,
  review_quality integer,
  review_productivity integer,
  review_teamwork integer,
  review_rating text,
  review_comments text,
  review_cycle_id bigint default null
)
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
  review_id bigint;
begin
  if not public.has_hrms_role(array['admin', 'hr_admin']) then
    raise exception 'HR administrator access required';
  end if;
  if review_score not between 0 and 100
     or review_goal_progress not between 0 and 100
     or review_quality not between 0 and 100
     or review_productivity not between 0 and 100
     or review_teamwork not between 0 and 100 then
    raise exception 'Performance values must be between 0 and 100';
  end if;

  insert into public.performance_reviews
    (
      employee_code, reviewer_code, cycle_id, period, score, goal_progress,
      quality_score, productivity_score, teamwork_score, rating, comments, status,
      published_at
    )
  values
    (
      target_employee, public.current_employee_code(), review_cycle_id, trim(review_period),
      review_score, review_goal_progress, review_quality, review_productivity,
      review_teamwork, trim(review_rating), nullif(trim(review_comments), ''), 'Draft', null
    )
  on conflict (employee_code, period) do update set
    reviewer_code = excluded.reviewer_code,
    cycle_id = excluded.cycle_id,
    score = excluded.score,
    goal_progress = excluded.goal_progress,
    quality_score = excluded.quality_score,
    productivity_score = excluded.productivity_score,
    teamwork_score = excluded.teamwork_score,
    rating = excluded.rating,
    comments = excluded.comments,
    status = 'Draft',
    published_at = null
  returning id into review_id;

  return review_id;
end;
$$;

create or replace function public.publish_performance_review(selected_review_id bigint)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  review_employee text;
  review_period text;
begin
  if not public.has_hrms_role(array['admin', 'hr_admin']) then
    raise exception 'HR administrator access required';
  end if;

  update public.performance_reviews
  set status = 'Published', published_at = now()
  where id = selected_review_id
    and status = 'Draft'
  returning employee_code, period into review_employee, review_period;

  if review_employee is null then raise exception 'Draft performance review not found'; end if;

  perform public.notify_employee(
    review_employee,
    'Performance',
    'Performance review published',
    'Your ' || review_period || ' review is ready.',
    'growth',
    'View review'
  );
end;
$$;

-- ---------------------------------------------------------------------------
-- Fictional demonstration records. These are database rows—not browser seed
-- state—and are visible only through the RLS rules above.
-- ---------------------------------------------------------------------------

insert into public.performance_cycles
  (title, period, status, start_date, end_date, created_by)
values
  ('Quarterly Performance Cycle', 'Q2 2026', 'Closed', '2026-04-01', '2026-06-30', 'EMP002')
on conflict (period) do update set
  title = excluded.title,
  status = excluded.status,
  start_date = excluded.start_date,
  end_date = excluded.end_date;

update public.performance_reviews review
set cycle_id = cycle.id,
    status = 'Published',
    published_at = coalesce(review.published_at, review.created_at)
from public.performance_cycles cycle
where review.period = cycle.period
  and review.cycle_id is null;

insert into public.payroll_runs
  (
    period, deduction_rate, status, employee_count, gross_total, net_total,
    created_by, approved_by, approved_at, released_at
  )
select
  'August 2026',
  8.25,
  'Released',
  count(*)::integer,
  coalesce(sum(gross + allowances + bonuses), 0),
  coalesce(sum(net), 0),
  'EMP002',
  'EMP002',
  now() - interval '2 days',
  now() - interval '1 day'
from public.payroll
where period = 'August 2026'
on conflict (period) do nothing;

update public.payroll payroll_record
set payroll_run_id = payroll_run.id,
    status = case when payroll_record.status = 'Draft' then 'Draft' else 'Released' end
from public.payroll_runs payroll_run
where payroll_record.period = payroll_run.period
  and payroll_record.payroll_run_id is null;

insert into public.work_schedules
  (employee_code, work_date, shift_start, shift_end, location, work_mode, notes)
select
  profile.employee_code,
  schedule_day::date,
  case when extract(isodow from schedule_day) in (6, 7) then '00:00'::time else '08:00'::time end,
  case when extract(isodow from schedule_day) in (6, 7) then '00:00'::time else '17:00'::time end,
  case when extract(isodow from schedule_day) in (6, 7) then 'Not scheduled' else 'Main Office' end,
  case when extract(isodow from schedule_day) in (6, 7) then 'Rest Day' else 'Hybrid' end,
  case when extract(isodow from schedule_day) in (6, 7) then 'Regular rest day' else 'Core hours: 9:00 AM–4:00 PM' end
from public.profiles profile
cross join generate_series(current_date, current_date + 13, interval '1 day') schedule_day
where profile.status = 'Active'
  and profile.role = 'employee'
on conflict (employee_code, work_date) do nothing;

insert into public.employee_benefits
  (employee_code, benefit_type, provider, plan_name, employee_share, employer_share, status, effective_date)
select employee_code, 'Health', 'Quantum Care Network', 'Standard Medical Plan', 650, 1850, 'Active', hire_date
from public.profiles
where role = 'employee'
on conflict (employee_code, benefit_type, plan_name) do nothing;

insert into public.employee_benefits
  (employee_code, benefit_type, provider, plan_name, employee_share, employer_share, status, effective_date)
select employee_code, 'Government', 'Statutory Benefits', 'SSS · PhilHealth · Pag-IBIG', 1450, 1450, 'Active', hire_date
from public.profiles
where role = 'employee'
on conflict (employee_code, benefit_type, plan_name) do nothing;

insert into public.employee_goals
  (employee_code, title, description, category, progress, status, due_date, created_by)
select employee_code,
       'Complete role capability plan',
       'Finish the agreed learning activities and demonstrate the capability in regular work.',
       'Growth',
       case employee_code when 'EMP001' then 68 when 'EMP003' then 82 else 54 end,
       'Active',
       current_date + 45,
       'EMP002'
from public.profiles
where role = 'employee'
  and not exists (
    select 1 from public.employee_goals existing
    where existing.employee_code = profiles.employee_code
      and existing.title = 'Complete role capability plan'
  );

insert into public.employee_documents
  (
    employee_code, title, document_type, period, content, filename, version,
    requires_ack, sensitive, uploaded_by
  )
select
  null,
  'Information Security and Acceptable Use Policy',
  'Policy',
  '2026',
  'Use company systems only for authorized work. Protect passwords, verify unusual sign-in activity, report suspected phishing promptly, and handle employee information according to your assigned role. Access is logged and reviewed.',
  'information-security-policy-2026.txt',
  '2.0',
  true,
  false,
  'EMP002'
where not exists (
  select 1 from public.employee_documents
  where title = 'Information Security and Acceptable Use Policy' and version = '2.0'
);

insert into public.employee_documents
  (
    employee_code, title, document_type, period, content, filename, version,
    requires_ack, sensitive, uploaded_by
  )
select
  null,
  'Employee Handbook',
  'Policy',
  '2026',
  'This handbook summarizes workplace expectations, attendance, leave, payroll, benefits, performance, respectful conduct, data privacy, and ways to request help from Human Resources.',
  'employee-handbook-2026.txt',
  '1.0',
  true,
  false,
  'EMP002'
where not exists (
  select 1 from public.employee_documents
  where title = 'Employee Handbook' and version = '1.0'
);

insert into public.employee_documents
  (
    employee_code, title, document_type, period, content, filename, version,
    requires_ack, sensitive, uploaded_by
  )
select
  'EMP001',
  'Certificate of Employment',
  'Certificate',
  '2026',
  'This fictional certificate confirms that David Santos is an active Operations Specialist of Quantum Art Resources for classroom demonstration purposes.',
  'EMP001-certificate-of-employment.txt',
  '1.0',
  false,
  true,
  'EMP002'
where not exists (
  select 1 from public.employee_documents
  where employee_code = 'EMP001' and title = 'Certificate of Employment'
);

insert into public.employee_requests
  (
    employee_code, request_type, subject, description, requested_date,
    requested_value, priority, status, assigned_to, decision_note, created_at
  )
select
  'EMP001',
  'Attendance Correction',
  'Missing clock-out for Monday',
  'I completed my shift but the clock-out did not appear in my attendance history.',
  current_date - 1,
  'Requested clock-out: 5:06 PM',
  'High',
  'Under Review',
  'EMP002',
  'HR is comparing the request with the daily attendance record.',
  now() - interval '8 hours'
where not exists (
  select 1 from public.employee_requests
  where employee_code = 'EMP001' and subject = 'Missing clock-out for Monday'
);

insert into public.request_comments (request_id, author_employee_code, body, is_internal, created_at)
select request.id,
       'EMP002',
       'Your request is being reviewed. No additional information is needed right now.',
       false,
       now() - interval '6 hours'
from public.employee_requests request
where request.employee_code = 'EMP001'
  and request.subject = 'Missing clock-out for Monday'
  and not exists (
    select 1 from public.request_comments comment
    where comment.request_id = request.id
      and comment.body = 'Your request is being reviewed. No additional information is needed right now.'
  );

insert into public.lifecycle_cases
  (employee_code, case_type, status, target_date, owner_code)
select 'EMP004', 'Onboarding', 'Active', current_date + 7, 'EMP002'
where not exists (
  select 1 from public.lifecycle_cases
  where employee_code = 'EMP004' and case_type = 'Onboarding' and status in ('Draft', 'Active')
);

insert into public.lifecycle_tasks (case_id, title, category, status, employee_visible, completed_by, completed_at)
select lifecycle_case.id,
       task.title,
       task.category,
       task.status,
       task.employee_visible,
       case when task.status = 'Complete' then 'EMP002' else null end,
       case when task.status = 'Complete' then now() - interval '1 day' else null end
from public.lifecycle_cases lifecycle_case
cross join (values
  ('Confirm employee profile', 'People', 'Complete', true),
  ('Provision least-privilege HRMS access', 'Access', 'Complete', false),
  ('Acknowledge required policies', 'Compliance', 'Pending', true),
  ('Complete team orientation', 'Experience', 'Pending', true)
) as task(title, category, status, employee_visible)
where lifecycle_case.employee_code = 'EMP004'
  and lifecycle_case.case_type = 'Onboarding'
  and lifecycle_case.status = 'Active'
  and not exists (
    select 1 from public.lifecycle_tasks existing
    where existing.case_id = lifecycle_case.id and existing.title = task.title
  );

insert into public.notifications
  (employee_code, category, title, message, destination, action_label, created_at)
select 'EMP001', 'Action', 'Policy acknowledgement required',
       'Review and acknowledge the updated Information Security and Acceptable Use Policy.',
       'documents', 'Review policy', now() - interval '2 hours'
where not exists (
  select 1 from public.notifications
  where employee_code = 'EMP001' and title = 'Policy acknowledgement required'
);

insert into public.notifications
  (employee_code, category, title, message, destination, action_label, created_at)
select 'EMP001', 'Request', 'Attendance request is under review',
       'HR is reviewing your missing clock-out request.',
       'requests', 'View request', now() - interval '6 hours'
where not exists (
  select 1 from public.notifications
  where employee_code = 'EMP001' and title = 'Attendance request is under review'
);

-- ---------------------------------------------------------------------------
-- Notifications and audit trail triggers
-- ---------------------------------------------------------------------------

create or replace function public.notify_announcement_recipients()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.notifications
    (employee_code, category, title, message, destination, action_label)
  select employee_code, 'Announcement', new.title, new.content, 'home', 'Read update'
  from public.profiles
  where status in ('Active', 'On Leave') and role = 'employee';
  return new;
end;
$$;

drop trigger if exists notify_announcement_recipients on public.announcements;
create trigger notify_announcement_recipients
  after insert on public.announcements
  for each row execute procedure public.notify_announcement_recipients();

create or replace function public.notify_document_recipient()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.notifications
    (employee_code, category, title, message, destination, action_label)
  select profile.employee_code,
         'Document',
         case when new.requires_ack then 'Document requires acknowledgement' else 'New document available' end,
         new.title || ' is now available in your document vault.',
         'documents',
         'View document'
  from public.profiles profile
  where profile.status in ('Active', 'On Leave')
    and profile.role = 'employee'
    and (new.employee_code is null or profile.employee_code = new.employee_code);
  return new;
end;
$$;

drop trigger if exists notify_document_recipient on public.employee_documents;
create trigger notify_document_recipient
  after insert on public.employee_documents
  for each row execute procedure public.notify_document_recipient();

create or replace function public.record_hrms_audit()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  actor_code text := public.current_employee_code();
  actor_name text;
  row_payload jsonb;
  target_label text;
begin
  if (select auth.uid()) is null then
    if tg_op = 'DELETE' then return old; end if;
    return new;
  end if;

  select concat(first_name, ' ', last_name)
  into actor_name
  from public.profiles
  where employee_code = actor_code;

  row_payload := case when tg_op = 'DELETE' then to_jsonb(old) else to_jsonb(new) end;
  target_label := coalesce(
    row_payload ->> 'employee_code',
    row_payload ->> 'alert_code',
    row_payload ->> 'session_code',
    row_payload ->> 'title',
    case when row_payload ? 'id' then replace(tg_table_name, '_', ' ') || ' ' || (row_payload ->> 'id') end,
    replace(tg_table_name, '_', ' ')
  );

  insert into public.audit_logs
    (actor_employee_code, actor_label, action, target, display_time)
  values
    (
      actor_code,
      coalesce(actor_name, 'Authenticated user'),
      initcap(lower(tg_op)) || ' ' || replace(tg_table_name, '_', ' '),
      target_label,
      to_char(timezone('Asia/Manila', now()), 'Mon DD, YYYY HH12:MI AM')
    );

  if tg_op = 'DELETE' then return old; end if;
  return new;
end;
$$;

do $$
declare
  target_table text;
begin
  foreach target_table in array array[
    'profiles', 'attendance', 'leave_requests', 'payroll', 'performance_reviews',
    'announcements', 'security_alerts', 'account_sessions', 'employee_requests',
    'request_comments', 'employee_documents', 'document_acknowledgements',
    'work_schedules', 'employee_benefits', 'employee_goals', 'lifecycle_cases',
    'lifecycle_tasks', 'payroll_runs', 'performance_cycles'
  ]
  loop
    execute format('drop trigger if exists %I on public.%I', 'audit_' || target_table, target_table);
    execute format(
      'create trigger %I after insert or update or delete on public.%I for each row execute procedure public.record_hrms_audit()',
      'audit_' || target_table,
      target_table
    );
  end loop;
end $$;

-- ---------------------------------------------------------------------------
-- Explicit grants. No HR table or workflow is available to anonymous users.
-- ---------------------------------------------------------------------------

revoke all on all tables in schema public from anon, authenticated;
revoke all on all sequences in schema public from anon, authenticated;

grant select on public.profiles to authenticated;
grant select on public.attendance to authenticated;
grant select on public.leave_requests to authenticated;
grant select on public.payroll to authenticated;
grant select on public.performance_reviews to authenticated;
grant select on public.announcements to authenticated;
grant select on public.security_alerts to authenticated;
grant select on public.account_sessions to authenticated;
grant select on public.audit_logs to authenticated;
grant select on public.employee_requests to authenticated;
grant select on public.request_comments to authenticated;
grant select on public.notifications to authenticated;
grant select on public.employee_documents to authenticated;
grant select on public.document_acknowledgements to authenticated;
grant select on public.work_schedules to authenticated;
grant select on public.employee_benefits to authenticated;
grant select on public.employee_goals to authenticated;
grant select on public.lifecycle_cases to authenticated;
grant select on public.lifecycle_tasks to authenticated;
grant select on public.payroll_runs to authenticated;
grant select on public.performance_cycles to authenticated;

grant update (phone, position, status, department, salary) on public.profiles to authenticated;
grant insert on public.announcements to authenticated;
grant update (status, updated_at) on public.security_alerts to authenticated;
grant delete on public.account_sessions to authenticated;
grant insert, update on public.employee_documents to authenticated;
grant insert, update, delete on public.work_schedules to authenticated;
grant insert, update, delete on public.employee_benefits to authenticated;
grant insert, update, delete on public.employee_goals to authenticated;
grant insert, update, delete on public.performance_cycles to authenticated;

grant usage, select on all sequences in schema public to authenticated;

revoke all on function public.current_hrms_role() from public, anon;
revoke all on function public.has_hrms_role(text[]) from public, anon;
revoke all on function public.is_active_hrms_user() from public, anon;
revoke all on function public.notify_employee(text, text, text, text, text, text) from public, anon, authenticated;
revoke all on function public.submit_employee_request(text, text, text, date, text, text) from public, anon;
revoke all on function public.add_request_comment(bigint, text, boolean) from public, anon;
revoke all on function public.cancel_employee_request(bigint) from public, anon;
revoke all on function public.review_employee_request(bigint, text, text) from public, anon;
revoke all on function public.mark_notification_read(bigint) from public, anon;
revoke all on function public.mark_all_notifications_read() from public, anon;
revoke all on function public.acknowledge_document(bigint) from public, anon;
revoke all on function public.update_goal_progress(bigint, integer) from public, anon;
revoke all on function public.create_lifecycle_case(text, text, date) from public, anon;
revoke all on function public.update_lifecycle_task(bigint, text) from public, anon;
revoke all on function public.review_leave_request(bigint, text) from public, anon;
revoke all on function public.generate_payroll(text, numeric) from public, anon;
revoke all on function public.transition_payroll_run(bigint, text) from public, anon;
revoke all on function public.save_performance_review(text, text, integer, integer, integer, integer, integer, text, text, bigint) from public, anon;
revoke all on function public.publish_performance_review(bigint) from public, anon;
revoke all on function public.set_hrms_updated_at() from public, anon, authenticated;
revoke all on function public.notify_announcement_recipients() from public, anon, authenticated;
revoke all on function public.notify_document_recipient() from public, anon, authenticated;
revoke all on function public.record_hrms_audit() from public, anon, authenticated;

grant execute on function public.current_hrms_role() to authenticated;
grant execute on function public.has_hrms_role(text[]) to authenticated;
grant execute on function public.is_active_hrms_user() to authenticated;
grant execute on function public.submit_employee_request(text, text, text, date, text, text) to authenticated;
grant execute on function public.add_request_comment(bigint, text, boolean) to authenticated;
grant execute on function public.cancel_employee_request(bigint) to authenticated;
grant execute on function public.review_employee_request(bigint, text, text) to authenticated;
grant execute on function public.mark_notification_read(bigint) to authenticated;
grant execute on function public.mark_all_notifications_read() to authenticated;
grant execute on function public.acknowledge_document(bigint) to authenticated;
grant execute on function public.update_goal_progress(bigint, integer) to authenticated;
grant execute on function public.create_lifecycle_case(text, text, date) to authenticated;
grant execute on function public.update_lifecycle_task(bigint, text) to authenticated;
grant execute on function public.review_leave_request(bigint, text) to authenticated;
grant execute on function public.generate_payroll(text, numeric) to authenticated;
grant execute on function public.transition_payroll_run(bigint, text) to authenticated;
grant execute on function public.save_performance_review(text, text, integer, integer, integer, integer, integer, text, text, bigint) to authenticated;
grant execute on function public.publish_performance_review(bigint) to authenticated;
