-- Role-aware Unified Security Center.
-- Employees own their MFA, sessions, alert responses, and personal timeline.
-- Authorized security roles receive organization-wide investigation and ZAP evidence.

alter table public.security_alerts
  add column if not exists why_it_matters text not null default 'Unexpected activity can indicate unauthorized access to an account or sensitive HR information.',
  add column if not exists assigned_to text references public.profiles(employee_code) on delete set null,
  add column if not exists resolution_reason text,
  add column if not exists resolution_notes text,
  add column if not exists acknowledged_at timestamptz,
  add column if not exists resolved_at timestamptz,
  add column if not exists confidence text not null default 'Medium'
    check (confidence in ('High', 'Medium', 'Low'));

alter table public.security_alerts drop constraint if exists security_alerts_status_check;
alter table public.security_alerts
  add constraint security_alerts_status_check
  check (status in ('New', 'Investigating', 'Acknowledged', 'Confirmed', 'Contained', 'Resolved', 'False Positive'));

alter table public.account_sessions
  add column if not exists last_seen_at timestamptz not null default now(),
  add column if not exists assurance_level text not null default 'aal1'
    check (assurance_level in ('aal1', 'aal2')),
  add column if not exists trust_status text not null default 'Recognized'
    check (trust_status in ('Recognized', 'Review Needed', 'Revoked'));

create table if not exists public.security_alert_responses (
  id bigint generated by default as identity primary key,
  alert_code text not null references public.security_alerts(alert_code) on delete cascade,
  actor_employee_code text not null references public.profiles(employee_code) on delete cascade,
  response_action text not null check (response_action in (
    'This was me', 'This was not me', 'Reviewed', 'Investigation started',
    'Session revoked', 'Contained', 'Resolved', 'False positive'
  )),
  note text,
  created_at timestamptz not null default now()
);

create index if not exists security_alert_responses_alert_idx
  on public.security_alert_responses (alert_code, created_at desc);

create table if not exists public.zap_scan_runs (
  scan_code text primary key,
  scan_type text not null check (scan_type in ('Baseline', 'Full', 'API', 'Authenticated')),
  environment text not null check (environment in ('Production', 'Deploy Preview', 'Staging', 'Local Test')),
  target_url text not null,
  zap_version text,
  started_at timestamptz,
  completed_at timestamptz not null default now(),
  status text not null default 'Review Needed' check (status in ('Passed', 'Review Needed', 'Failed', 'Accepted Risk')),
  high_count integer not null default 0 check (high_count >= 0),
  medium_count integer not null default 0 check (medium_count >= 0),
  low_count integer not null default 0 check (low_count >= 0),
  informational_count integer not null default 0 check (informational_count >= 0),
  report_name text,
  report_sha256 text,
  authorized_scope text not null,
  reviewed_by text references public.profiles(employee_code) on delete set null,
  reviewed_at timestamptz,
  notes text,
  created_at timestamptz not null default now()
);

create table if not exists public.zap_findings (
  id bigint generated by default as identity primary key,
  scan_code text not null references public.zap_scan_runs(scan_code) on delete cascade,
  plugin_id text,
  name text not null,
  risk text not null check (risk in ('High', 'Medium', 'Low', 'Informational')),
  confidence text not null default 'Medium',
  description text,
  solution text,
  reference_url text,
  affected_url text,
  evidence text,
  status text not null default 'Open' check (status in ('Open', 'In Progress', 'Remediated', 'Accepted Risk', 'False Positive')),
  created_at timestamptz not null default now()
);

create index if not exists zap_findings_scan_idx on public.zap_findings (scan_code, risk, status);

alter table public.security_alert_responses enable row level security;
alter table public.zap_scan_runs enable row level security;
alter table public.zap_findings enable row level security;

drop policy if exists security_alert_responses_select on public.security_alert_responses;
create policy security_alert_responses_select on public.security_alert_responses
  for select to authenticated
  using (
    exists (
      select 1 from public.security_alerts alert
      where alert.alert_code = security_alert_responses.alert_code
        and alert.employee_code = public.current_employee_code()
    )
    or public.has_hrms_role(array['admin', 'security_admin', 'auditor'])
  );

drop policy if exists zap_scan_runs_select on public.zap_scan_runs;
create policy zap_scan_runs_select on public.zap_scan_runs
  for select to authenticated
  using (public.has_hrms_role(array['admin', 'security_admin', 'auditor']));

drop policy if exists zap_findings_select on public.zap_findings;
create policy zap_findings_select on public.zap_findings
  for select to authenticated
  using (public.has_hrms_role(array['admin', 'security_admin', 'auditor']));

grant select on public.security_alert_responses, public.zap_scan_runs, public.zap_findings to authenticated;

create or replace function public.respond_to_security_alert(
  selected_alert_code text,
  response_action text,
  response_note text default null
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  employee text := public.current_employee_code();
  next_status text;
begin
  if employee is null or not public.is_active_hrms_user() then
    raise exception 'Active authentication is required';
  end if;
  if response_action not in ('This was me', 'This was not me', 'Reviewed', 'Session revoked') then
    raise exception 'Unsupported account-security response';
  end if;

  if not exists (
    select 1 from public.security_alerts
    where alert_code = selected_alert_code and employee_code = employee
  ) then
    raise exception 'Account alert not found';
  end if;

  next_status := case
    when response_action in ('This was me', 'Reviewed') then 'Acknowledged'
    else 'Investigating'
  end;

  update public.security_alerts
  set status = next_status,
      acknowledged_at = case when next_status = 'Acknowledged' then now() else acknowledged_at end,
      updated_at = now()
  where alert_code = selected_alert_code;

  insert into public.security_alert_responses
    (alert_code, actor_employee_code, response_action, note)
  values
    (selected_alert_code, employee, response_action, nullif(trim(response_note), ''));
end;
$$;

revoke all on function public.respond_to_security_alert(text, text, text) from public, anon;
grant execute on function public.respond_to_security_alert(text, text, text) to authenticated;

do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'security_alert_responses'
  ) then
    alter publication supabase_realtime add table public.security_alert_responses;
  end if;
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'zap_scan_runs'
  ) then
    alter publication supabase_realtime add table public.zap_scan_runs;
  end if;
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'zap_findings'
  ) then
    alter publication supabase_realtime add table public.zap_findings;
  end if;
end $$;
